### ISSUE TITLE
Allow defining background color on Container

### ISSUE THREAD

**Issue by Alphare** [hecrj/iced#112]
Right now I think it's only possible to set the background color on a button. 
It makes sense to be able to add background colors (and any other style for that matter) on anything that makes sense.

**Comment by hecrj** [comment]
Styling overall is missing. It's something that we still have to figure out and decide on a solution.

We have [a Zulip thread](https://iced.zulipchat.com/#narrow/stream/213316-general/topic/styling) where we shared some ideas. I will start exploring this soon.

**Comment by norman784** [comment]
IMHO the base widget (that seems to be the `Container` widget) need to implement all the common properties between widgets, border (color, width, rounder corders), shadow, background, width, height, padding, etc so you don't need to reimplement it in each one or in a few, also one big advantage I find in this approach is that you can do a lot of things with even images (because they inherits from `Container`? I didn't checked in deep how and if there is a inheritance there or what's the rust way to do it).

My problem using similar UI libraries in the past was that one (iOS) was build this way, while the other (android) wasn't so in order to achieve simple things that you could with some widgets you need to reimplement the i.e. Image widget, etc.

Also you need to expose all the internals so we can freely create custom widgets, there are some methods, properties that has `pub(crate)` so it makes hard to create custom ones.

Last note, I'm impressed by the achievements on this library, is amazing how easy it seems to use, even I can understand (or that's what I think) how the widgets were implemented, while in the past I struggle to understand some crates out there.

Cheers

**Comment by gabrieldechichi** [comment]
Is this actually closed? At this time the `Background` enum only supports `Color`. On `core/src/background.rs`

```
use crate::Color;

/// The background of some element.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Background {
    /// A solid color
    Color(Color),
    // TODO: Add gradient and image variants
}
```
