### ISSUE TITLE
Crashes with assertion failed

### ISSUE THREAD

**Issue by pickx** [hecrj/iced#148]
Unfortunately, whenever I try to run any example, a window pops up then immediately closes with the following assertion failure

```
thread 'main' panicked at 'assertion failed: suf.supports_queue_family(&adapter.raw.queue_families[0])', /home/{USER}/.cargo/registry/src/{...}/wgpu-native-0.4.2/src/device.rs:2065:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I'm assuming this has to do with the environment I'm running this in? I'm using Linux Manjaro with a GTX 1080 and a Coffee Lake CPU.

**Comment by hecrj** [comment]
Most likely a graphics driver issue, may be related to #98 or #79. Ensure you have Vulkan-compatible graphics drivers installed.

**Comment by pickx** [comment]
Yeah, I think it's Vulkan. Unfortunately I spend a lot of times trying to get Vulkan support with nVidia graphics on Manjaro, but no dice.

**Comment by pickx** [comment]
Yeah, I think it's Vulkan. Tried some other Vulkan demos and they don't work either.
I spent a lot of time trying to get Vulkan support with nVidia graphics on Manjaro, but no dice.

**Comment by AlisCode** [comment]
Ho yes I'm having the same issue on my main computer : my CPU is an old i5-4670k (Haswell) and the drivers don't have a correct Vulkan implementation, not one that works with wgpu anyway.

The way I test the iced (wgpu backend) examples right now on this setup is by applying this patch : 

```
diff --git a/wgpu/src/renderer.rs b/wgpu/src/renderer.rs
index 6f35e24..a4a910c 100644
--- a/wgpu/src/renderer.rs
+++ b/wgpu/src/renderer.rs
@@ -55,7 +55,7 @@ impl<'a> Layer<'a> {
 impl Renderer {
     fn new(settings: Settings) -> Self {
         let adapter = Adapter::request(&RequestAdapterOptions {
-            power_preference: PowerPreference::Default,
+            power_preference: PowerPreference::HighPerformance,
             backends: BackendBit::all(),
         })
         .expect("Request adapter");
```

Then my "high performance" (i.e. nvidia) drivers does its magic and everything is flawless.
On Manjaro you can get them with `sudo pacman -S nvidia`. I don't use nouveau, maybe that's your problem ? 

If this issue is to be fixed someday, I think it would be on the wgpu side.
