### ISSUE TITLE
Async Application::update

### ISSUE THREAD

**Issue by fenhl** [hecrj/iced#153]
It would make things a lot easier if the `Application::update` trait method were `async`, so that you can both use `.await` and mutate the `Application`.

# Workaround

Use [`block_on`](https://docs.rs/async-std/1.4.0/async_std/task/fn.block_on.html) instead of `.await`.

**Comment by hecrj** [comment]
Say we are awaiting for a request to finish and the user clicks a button. How would we change state 
while awaiting?

**Comment by fenhl** [comment]
The API doesn't actually need to be parallelized, just `async`-compatible.

**Comment by hecrj** [comment]
I am not sure I follow. We cannot make the application unresponsive while awaiting for something to complete.

**Comment by fenhl** [comment]
Doesn't that already happen now, since `update` isn't `async`?

**Comment by hecrj** [comment]
No. This issue is introduced when you make `update` async, as you suddenly tie the `Application` state to the returned future.

The current `update` returns a `Command` which is just a bunch of static futures that produce messages as results. They cannot mutate the `Application` state, therefore the borrow checker lets us call `update` again while they run.

**Comment by fenhl** [comment]
I'm not proposing to change the return type, other than wrapping it in a future by way of the `async` sugar.

**Comment by hecrj** [comment]
Async actions should not make the application unresponsive. The current design is tailored to enforce this.

**Comment by fenhl** [comment]
I'm not actually using any async actions. The interface just needs to be `async` because of requirements of an unrelated usage.

**Comment by hecrj** [comment]
I have explained why the interface cannot be async. You should not be allowed to await and tie the `Application` state to it because you would block the whole `Application`.

I have the feeling this is going nowhere. Maybe you could elaborate a bit more your use case? You stated:

> It would make things a lot easier if the Application::update trait method were async, so that you can both use .await and mutate the Application.

Do we agree that this should not be possible?

**Comment by fenhl** [comment]
There appears to be some sort of issue with adding this in general that I don't understand, so I opted to use [`block_on`](https://docs.rs/async-std/1.4.0/async_std/task/fn.block_on.html) as a workaround.

**Comment by hecrj** [comment]
Why not just return a `Command`? That's how you are supposed to perform async tasks. For instance, check [the `pokedex` example](https://github.com/hecrj/iced/blob/master/examples/pokedex.rs#L35). You can create a `Commad` from a future easily: https://docs.rs/iced/0.1.0-beta/iced/struct.Command.html#method.perform

You will not be able to mutate the `Application` state inside a `Command`, though. As I have already explained multiple times, this would block the `Application`. However, you will get notified of its results once the futures finish.

**Comment by 0xJepsen** [comment]
Hey i am looking for this example but it seems that it is no longer at this location.

**Comment by mominul** [comment]
@0xJepsen [It is the mentioned line](https://github.com/iced-rs/iced/blob/f5c6fa7338713a0430dcdfc5bd53f72103144f22/examples/pokedex/src/main.rs#L64)
