### ISSUE TITLE
Weird behavior in tour demo when switching between rows and columns

### ISSUE THREAD

**Issue by anchpop** [hecrj/iced#174]
[You can hopefully see the issue here](https://gfycat.com/LiquidDamagedCommongonolek). When I press-and-hold the radio button to switch between the column and the row layout, the whole layout kind of gets weird and disorganized. 

This is using the `tour` demo downloaded from the latest master, run in release, on Windows. My rustc version is 1.42.0-nightly. 

Also, performance is not very good on my surface laptop which you can see when the slider kind of lags behind my mouse cursor at the end :( but I know this project is in the early stages and performance is probably more of a long-term goal. It is perfectly responsive in the web build (the column switching issue doesn't happen either). Iced is still pretty amazing! ❤️

**Comment by hecrj** [comment]
It looks like a graphical glitch. What kind of GPU are you using? Are your drivers up-to-date?

The performance issue you mention may be V-sync adding latency. You can enable the debug view to see some performance metrics by pressing `F12`.

We will eventually implement a CPU and/or OpenGL renderer which should be a better choice when using integrated GPUs.

**Comment by anchpop** [comment]
Hi, 
Yeah, there's actually a few graphical glitches besides the one I showed, I can take screenshots if you want. My drivers should be up to date and I'm using the Surface's integrated graphics. Maybe once wgpu gets OpenGL support it'll work better but it does support Vulkan and DX12. With the same setup on my desktop (Nvidia GPU) it works fine and there's very little latency. 

For some reason, it wasn't building on stable rust. Maybe I was using an old version, I can try again if you think it'll make a difference.

**Comment by hecrj** [comment]
The issue looks like some kind of buffer corruption/data race. It seems data from the previous frame is leaking to the next one.

Yes, it may be a good idea to try it on `stable` Rust. Additionally, you could try the [`wgpu`] and [`wgpu_glyph`] examples to help me discard any issues upstream.

[`wgpu`]: https://github.com/gfx-rs/wgpu-rs
[`wgpu_glyph`]: https://github.com/hecrj/wgpu_glyph

**Comment by parasyte** [comment]
FWIW, the latency can be improved greatly with two minor changes:

1. Make sure antialiasing is enabled in the backend, to force `wgpu` to use the highest performance GPU available (this is optional):
  https://github.com/hecrj/iced/blob/9758c121764a6e8e5a45b8a66915127b31e61df7/wgpu/src/window/backend.rs#L24
2. Patch the swap chain to disable VSync:
  https://github.com/hecrj/iced/blob/9758c121764a6e8e5a45b8a66915127b31e61df7/wgpu/src/window/swap_chain.rs#L52

Use `present_mode: wgpu::PresentMode::NoVsync,` Note that this setting will cause image tearing when there is a lot of motion on the screen (like in a game or video player). This setting will have the greatest impact on reducing latency. (It's a tradeoff.)

Just sharing, since I spent about an hour or two trying to find a good way to reduce input latency.

**Comment by hecrj** [comment]
This is most likely fixed by the OpenGL renderer implemented in #354.

Feel free to reopen the issue if it persists!
