### ISSUE TITLE
problem while running compiled app

### ISSUE THREAD

**Issue by RustemB** [hecrj/iced#194]
```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running `target/debug/counter`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/instance.rs:474:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by hecrj** [comment]
This issue is caused by `wgpu` not being able to find a suitable graphics adapter. Similar issues have been reported in #182, #72 and/or https://github.com/hecrj/iced/issues/69#issuecomment-559673451.

`wgpu` has some issues running on old hardware. We will eventually implement an OpenGL/software renderer as a fallback. In the meantime, some users have been able to fix the issue by updating graphics drivers.

**Comment by MCOfficer** [comment]
See also https://github.com/gfx-rs/wgpu-rs/issues/226 - in my case it was a graphics driver upgrade that apparently broke vulkan. `vkcube` reveled the culprit, and a reboot fixed it.

**Comment by RustemB** [comment]
D:
