### ISSUE TITLE
Using wasm-bindgen get errors with example tour

### ISSUE THREAD

**Issue by cossonleo** [hecrj/iced#225]
I want to compile tour example to web platform and I follow the web/README.md, but I get a error:

cli: wasm-bindgen ../target/wasm32-unknown-unknown/debug/examples/tour.wasm --out-dir tour --web

error: failed to read `../target/wasm32-unknown-unknown/debug/examples/tour.wasm

And

cli: wasm-bindgen ../target/wasm32-unknown-unknown/debug/tour.wasm --out-dir tour --web

error: thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', crates/cli-support/src/descriptor.rs:202:15
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

wasm-bindgen: wasm-bindgen-0.2.59-x86_64-unknown-linux-musl binary.

**Comment by hecrj** [comment]
The first error is caused by the `README` being out-of-date since we packaged the examples as crates in #164. I just fixed it in https://github.com/hecrj/iced/commit/93f5640a2dc06d8f1bf2b0d033d45c62f8985380.

The second error looks like a [`wasm-bindgen`](https://github.com/rustwasm/wasm-bindgen) bug to me. I think you should report it there. I just tried and `wasm-bindgen 0.2.58` works fine for me.

**Comment by cossonleo** [comment]
Thx
