### ISSUE TITLE
"cargo run --package tour" opens a window, but it’s invisible

### ISSUE THREAD

**Issue by loewenheim** [hecrj/iced#257]
It took me a while to get everything compiling and running under NixOS. I can now compile and run the `tour` package, but I can’t see or interact with the window that (supposedly) opens. You can see in the attached screenshots that my desktop looks the same whether my terminal or the iced window is focused.

I’m using i3 on nixos-unstable. My graphics card is an onboard Intel device.
![iced_focused](https://user-images.githubusercontent.com/7622248/78389491-121ae580-75e3-11ea-886a-b15444126874.png)
![terminal_focused](https://user-images.githubusercontent.com/7622248/78389495-147d3f80-75e3-11ea-9f84-7be8d097e93b.png)

**Comment by hecrj** [comment]
Thanks for reporting!

Could you confirm if the same issue happens when you run any of the [`winit`] and/or [`wgpu`] examples?

> t took me a while to get everything compiling and running under NixOS

If you can provide more details about this process, it may help us find out what the problem is.

[`winit`]: https://github.com/rust-windowing/winit
[`wgpu`]: https://github.com/gfx-rs/wgpu-rs

**Comment by hecrj** [comment]
> All the wgpu examples I tried work, but the two winit examples I tried (timer and window_icon) exhibit exactly the same behavior as the iced one.

Both of these `winit` examples don't draw anything. I suspect the window is opened correctly, but nothing is being rendered to it so it stays transparent.

`wgpu` has evolved quite a bit since `0.4` (the one we use), could you try the examples in [the `0.4` branch](https://github.com/gfx-rs/wgpu-rs/tree/v0.4)? As I explained in #243, you will need to change [the last line of the `Cargo.toml`](https://github.com/gfx-rs/wgpu-rs/blob/v0.4/Cargo.toml#L41) to compile them:

```toml
winit = "=0.20.0-alpha4"
```

**Comment by loewenheim** [comment]
The `wgpu` examples still (already?) work in 0.4. Are there any specific `winit` examples I should test?

**Comment by hecrj** [comment]
`wgpu` is using `winit` for its examples. If they work for you, I believe we can discard any issues there.

My bet is that the current renderer is doing _something_ that is not supported by your graphics driver. I think the `vulkan-validation-layers` could help us identify the problem. Could you try installing them and then run the `tour` example in debug mode? Any errors/warnings should be printed in the terminal.

**Comment by loewenheim** [comment]
How do I run it in debug mode?

**Comment by hecrj** [comment]
Oh, sorry. I meant you should run it without the `--release` flag, just as you did in those screenshots.

**Comment by loewenheim** [comment]
Installing the validation layers does not seem to have made a difference. I’m not seeing any errors or warnings.

**Comment by hecrj** [comment]
Oh well, I am a bit clueless then. Some more questions worth to answer:

- Does the same issue happen with examples that enable antialiasing, like `clock` or `solar_system`?
- Is the window really invisible or is it visible but nothing is being drawn on it? Is there some way for you to find out? Maybe you could enable decorations, change the WM layout, or try moving/resizing the window.
- Could you try the [`wgpu_glyph`](https://github.com/hecrj/wgpu_glyph) examples too?

**Comment by loewenheim** [comment]
Ok, this is weird. I tried the `clock` example and initially got these results, in tabbed and split layout, respectively:
![clock](https://user-images.githubusercontent.com/7622248/78457109-37255c00-76a8-11ea-9334-2e3aa4d2d4eb.png)
![clock_split](https://user-images.githubusercontent.com/7622248/78457111-3bea1000-76a8-11ea-81c7-476a10904a6b.png)
I took screenshots and switched over to firefox to write this issue. When I switched back to the desktop with the terminal, the clock had appeared:
![clock_split2](https://user-images.githubusercontent.com/7622248/78457134-57edb180-76a8-11ea-94a0-e08a668d463b.png)
This made me try the `tour` and `solar_system` examples as well, and … everything works now. I can  open the windows, switch the desktop layout, turn them into floating windows, close them. I’m also not experiencing any delays or artifacts.

`tour` outputs an error, but I don’t know if it has anything to do with all this:
```
ERROR gfx_backend_vulkan]
    VALIDATION [VUID-VkSwapchainCreateInfoKHR-imageExtent-01274 (0)] : vkCreateSwapchainKHR() called with imageExtent = (1707,1280), which is outside the bounds returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR(): currentExtent = (950,1046), minImageExtent = (950,1046), maxImageExtent = (950,1046). The Vulkan spec states: imageExtent must be between minImageExtent and maxImageExtent, inclusive, where minImageExtent and maxImageExtent are members of the VkSurfaceCapabilitiesKHR structure returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR for the surface (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkSwapchainCreateInfoKHR-imageExtent-01274)
    object info: (type: DEVICE, hndl: 94518417843024)
```

**Comment by hecrj** [comment]
Hmm... It feels like we are dealing with some weird driver shenanigans.

[I think OpenGL support for `wgpu` will happen eventually](https://github.com/gfx-rs/wgpu/issues/450) and should solve most of these issues. I am also experimenting with different, more mature rendering alternatives.

> tour outputs an error, but I don’t know if it has anything to do with all this

I believe it's unrelated, although probably worthy of investigating further. This error happens when swapchain creation can't keep up with window resize events.

**Comment by loewenheim** [comment]
In any case, thank you very much for your assistance and for your work on `iced`, it looks extremely promising!
