### ISSUE TITLE
White screen on tour example

### ISSUE THREAD

**Issue by mattbradbury** [hecrj/iced#350]
When I run the tour example I'm only getting a white screen.  Every other example I've tried has worked.

I managed to get it working by removing the "image" feature requirement in Cargo.toml and commenting out the actual image loading in the ferris() function and replacing it with a Text widget instead.  Even with the image loading commented out, it's still white screens, only removing the feature requirement lets it work.

The pokedex example does work even though it includes the same "image" feature.  I'm stumped without diving deeper into the code.  I'm on Windows 10, older machine, Intel 4000 display and DirectX12.

Any advice on where to start looking in the code to help debug this?

**Comment by brainstorm** [comment]
Perhaps a duplicate issue of https://github.com/hecrj/iced/issues/342 ?

**Comment by hecrj** [comment]
@mattbradbury I am not sure what could be causing it.

The `image` feature allocates a texture atlas on initialization. If the `pokedex` example works for you, but the `tour` does not. The only that comes to mind is that you may be running out of video memory with the `tour` when the `image` feature is enabled, as it renders more text than the `pokedex`.

Also, the Intel HD Graphics 4000 [doesn't seem to support DirectX 12](https://www.intel.com/content/www/us/en/support/articles/000005524/graphics-drivers.html). DirectX 11 support for `wgpu` is still rough, so we may be hitting a weird edge case.

@brainstorm It doesn't seem related. That issue seems to only have problems with the MSAA blit pipeline.

**Comment by mattbradbury** [comment]
@hecrj Upon further review, pokedex is only half working.  I can see the pokemon image and it's text, but I don't see the button to search for another one.  I also don't see the Loading "Searching for Pokemon.." text.  So I was thinking that it was just something with the top-level view, and that incorporating a lower one would work somehow.  So I moved the search again button into the Pokemon::view() and I can't see it, but I can click it and it works as expected, just invisibly.

As to text taking up space, I stripped the tour example all the way down to a single Text("hello world") and a single button, and it didn't display until removing the "image" feature.

I took a closer look at my dxdiag output, and I see that DX12 is installed, but only has DX11 features.

I wish I had more modern hardware right now, but catastrophic water intake into laptops sets you back a bit :(  If it's just DX11 shenanigans, I can accept that and see what `wgpu` is doing.
