### ISSUE TITLE
Why release cadence isn't regular?

### ISSUE THREAD

**Issue by sum-elier** [hecrj/iced#538]
What's the reason behind a slow release cadence?

Was wondering if it would be possible to have weekly, bi weekly, or similar, release cadence because since the last release there have been so many nice improvements and fixes to the library, and even the examples, that it would be beneficial to integrate them with existing projects making use of this library. Right now, and I suspect I am may be wrong, the only 2 ways to integrate these new changes is by declaring the library dependency as either a git ref or as a path to a local version of the repository.

Having a faster release cadence allows to detect bugs faster, upgrade dependents easier, take advantage of the improvements and so forth. Unless, of course, there's a reason not to do it this way.

So, is this idea viable?

**Comment by valbendan** [comment]
I think a faster and predict release cadence is good for us.

Since the library is far from 1.0 version, user should NOT expect compatibility guarantees.

The 0.1 version has been around for a long time, and there are many features already in the dev branch。

Maybe @hecrj  have high standard, but at lease we can release alpha version and we can use feature gate to indicated the unstable features.

**Comment by GalAster** [comment]
Can a regular github action be used to update the patch version number every week.

Significant improvements and changelog can be given with the minor version number.
