### ISSUE TITLE
Error: GraphicsAdapterNotFound even with glow feature enabled

### ISSUE THREAD

**Issue by celsobonutti** [hecrj/iced#566]
I'm trying to run the `game_of_life` example (cloned from `master`) in Windows 10 using WSL2 + VcxSrv, also tried with X410.
I tried to do as said in #564 and enabled `glow`, also disable `Native OpenGL` in VcxSrv's configuration, but I'm still getting the `GraphicsAdapterNotFound` error.

The XServer is working fine for other applications.

**Comment by twitchyliquid64** [comment]
Are you able to run any of the openGL demo applications? Like glxgears?

**Comment by celsobonutti** [comment]
Yes I am, both `glxgears` and `glmark2`.

**Comment by celsobonutti** [comment]
Disabling antialiasing worked btw, I think this may something related to me gpu. I'll close this issue.

**Comment by tabedzki** [comment]
Hi all,
I've tried to do the clock examples in a Ubuntu 18.04 distro using both WSL and WSL 2.0 using VcXsrv while disabling `Native OpenGL` like suggested in VcXsrv but I still get the error of `GraphicsAdapterNotFound`. (I can't even compile in WSL 2.0 since rust installer rustup isn't working either.)

Are there any other suggestions for getting this to work in WSL 1.0? (Should this be a new issue?)

**Comment by ystyle** [comment]
i have the same issue

![2020-12-28_14-31](https://user-images.githubusercontent.com/4478635/103194092-660bee00-4919-11eb-9def-dd553e07818e.png)

**Comment by ystyle** [comment]
> i have the same issue
> 
> ![2020-12-28_14-31](https://user-images.githubusercontent.com/4478635/103194092-660bee00-4919-11eb-9def-dd553e07818e.png)

change dependencies to: 
```toml
[dependencies]
iced = { version = "0.2", features = ["glow", "tokio"] }
```

and i works

**Comment by twitchyliquid64** [comment]
@ystyle if you dont have vulkan drivers for your GPU you can try the `mesa-vulkan-drivers` package - it does a good job for commodity hardware (and then it should work without the `glow` feature on linux).
