### ISSUE TITLE
Use something other than `font-kit` and/or put it behind feature gate

### ISSUE THREAD

**Issue by termhn** [hecrj/iced#58]
`font-kit` seems like a nice lib, however it's very much *not* pure Rust, requiring not only a full c++ build system but also several C libs and their associated header files to be installed on a system (at least on Linux), and as such presents a fairly significant bar to entry. It would be nice not to depend on it. Also, even after getting it to compile on Fedora, I stlil get this output in my terminal when runing the `todos` example, though it does seem to work at least.

*edit*

error output was fixed by updating outdated `fontconfig-devel`.

Just for reference, on Fedora 30, I had to install `cmake`, `g++`, `freetype`, `freetype-devel`, `expat-devel`, and `fontconfig-devel` for it to work.

**Comment by hecrj** [comment]
This seems to be caused by `libfontconfig`, which compiles and statically links itself if it can't find an appropriate system version with `pkg-config`. Here is the relevant code: https://github.com/servo/libfontconfig/blob/master/build.rs#L20

That said, a feature gate would be nice for cases where system font loading isn't needed (for instance, when embedding fonts in games).

**Comment by AlienKevin** [comment]
Just in case someone on ubuntu wants to install these missing dependencies:
```
sudo apt install pkg-config
sudo apt install cmake
sudo apt install libfreetype6-dev
sudo apt-get install expat
sudo apt-get install libexpat-dev
```
After installing the above, the counter example builds successfully.

**Comment by myfreeweb** [comment]
https://github.com/servo/libfontconfig/issues/55 would add a `force_system_lib` feature to libfontconfig that would allow us to get an error instead of building the silly/annoying cache-incompatible embedded fontconfig
