### ISSUE TITLE
Height of nested columns is not calculated correctly

### ISSUE THREAD

**Issue by njust** [hecrj/iced#59]
Hi,

I'm playing around with iced. I tried GTK rs and OrbTK before. So far I like iced the most. Thanks a lot for all your hard work on that! 

I'm building a small test program to search files. The search results are limited to 100 and the user is able to fetch more results with a load more button on the bottom of the results. When clicking on a search result the programm will try to open the file with the associated default program.

Since I need to configure where to search I embedded the search mask into a small tab control. Now It seems that the height of the column inside the tab control does not calculate correctly, because the last five results or so are not visible and the scrollbar is cut off.

See screenshots here: 
https://www.notion.so/Search-UI-clipped-scrolbar-1dd435b4ee604e4ab4060971942becc7

For now I set the height of the inner column to fixed to fixed height of 600. If you want to reproduce the issue you can comment out that in line 113 of the /file_search/src/search.rs

The code can be found here
https://github.com/njust/file_search

Thank you again for such a great GUI library!

**Comment by hecrj** [comment]
Hey @njust, thanks for the kind words! I am glad you like the library and very happy to see interesting test apps being built with it!

This bug is caused by a wrong implementation of `Widget::height` in some widgets. I fixed it in #60.

However, [the current `flex` layout algorithm always uses the parent container max limits for children that does not have a `Length::Fill` in the main axis](https://github.com/hecrj/iced/blob/master/native/src/layout/flex.rs#L83). I am guessing we could subtract from that the size of the previous children to try to make content fit properly. I'll give it a bit more thought!

Therefore, in order to make it work for now, you will need to explicitly set the `height` of the column to `Length::Fill` (simply replace `Units(600)` with `Fill`).

**Comment by njust** [comment]
Thank you so much for the quick answer. Unfortunately it makes no difference if I leave out .height(Length::Units(600)) or use Length::Fill. Both times the scrollbar will be cut off.

**Comment by hecrj** [comment]
@njust Did you try it with the branch of #60? It should work with the fixes there. I just double checked, and these simple changes work as expected for me:

```diff
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -7,6 +7,6 @@ edition = "2018"
 # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
 
 [dependencies]
-iced = {git = "https://github.com/hecrj/iced.git"}
+iced = {git = "https://github.com/hecrj/iced.git", branch = "fix/required-width-height"}
```

```diff
--- a/src/search.rs
+++ b/src/search.rs
@@ -110,7 +110,7 @@ impl SearchUi {
         Column::new()
             .push(search_bar)
             .push(result_scrollable)
-            .height(Length::Units(600))
+            .height(Length::Fill)
             .into()
     }
```

**Comment by njust** [comment]
Sorry, I missed the fact, that it's fixed in a separate branch. I checked it with the branch and it works fine. Thank you very much!
