### ISSUE TITLE
 How to approach Drag and Drop?

### ISSUE THREAD

**Issue by geofmureithi** [hecrj/iced#82]
I want to create drag and drop similar to this one [Codepen](https://codepen.io/notepage/pen/XavXaE)
According to #61, I can't use gtk and I am wondering where to start.

**Comment by hecrj** [comment]
I think this should be achievable with a custom widget accepting a draggable set of items and containing a drop zone.

Once one of the items is clicked, you would draw it at the cursor position until it is dropped. If it is dropped in the drop zone, you could produce a `Message` containing the index of the dropped item.

The main limitation of this approach is that both draggable and drop zone will be part of the same widget and flexibility when it comes to styling may be difficult. This is necessary to control drawing properly because layers are not supported yet (see #30).

**Comment by geofmureithi** [comment]
Interesting, let me see if I can get something.

**Comment by hecrj** [comment]
The new `PaneGrid` widget (see #224) implements drag and drop with the approach I described in my previous comment.

**Comment by geofmureithi** [comment]
Awesome!
