### ISSUE TITLE
Add a SpinBox Widget

### ISSUE THREAD

**Issue by Luni-4** [hecrj/iced#869]
This is my first issue on this repository, so first of all thanks a lot to all the people contributing to this project! I like it a lot!

It would be helpful to add a `SpinBox` widget among the built-in widgets. Something like this: 

![image](https://user-images.githubusercontent.com/12353765/117299438-da7f0c80-ae78-11eb-8a5c-acf7ac042cf1.png)

It could also be added in the `counter` example to show how it works.

**Comment by 13r0ck** [comment]
#762 is POC PR for this feature. I haven't started working on it, but I have put a lot of thought into what would be the best way to implement this. Most "SpinBoxes" use integers, but I would like something more flexible. (For example using scientific notation for scientific applications). As well has have a configurable scroll delta (via scroll wheel or arrow keys).

Not that efficiency is _that_ big of an issue, because most modern computers have no issue handling some numbers, but I'm still not sure what would be the most efficient data structure, maybe passing in anything that `impl` `.iter()`, then interacting with the widget just creates a message from "iterating" on the data? I'm not a technical wizard, @hecrj any input on best way to implement this?

**Comment by Luni-4** [comment]
I'm not an expert either, but I would start with integers and later expand it to a definition that considers more complex numbers. For example, I would implement in this repository a `SpinBox` that handles `usize` and in the [`iced_aw`](https://github.com/iced-rs/iced_aw) the more complex `SpinBox` widgets you were proposing.

**Comment by Kaiden42** [comment]
The `NumberInput`, mentioned in #762, is was merged into [iced_aw](https://github.com/iced-rs/iced_aw) few days ago, but I haven't updated the readme yet.

**Comment by Luni-4** [comment]
Oh, I didn't know that too! 

Since it is already implemented in  [iced_aw](https://github.com/iced-rs/iced_aw), we can close this issue. Thanks @13r0ck and @Kaiden42 for the help! :smiley:
