### ISSUE TITLE
On Mac OS X the wrong cursor type is displayed when hovering over a slider

### ISSUE THREAD

**Issue by mlindner** [hecrj/iced#9]
When hovering over the slider the "hand with closed fingers" is displayed even before clicking. Normally that would transform to the "hand with closed fingers" when clicking and the "hand with open fingers" before clicking. I can't seem to take a screenshot of this however.

**Comment by hecrj** [comment]
Thanks for the report!

This is a `winit` issue, the windowing library that `ggez` uses. [It looks like both grabbing and grab cursors are being mapped to the same "closed hand cursor"](https://github.com/rust-windowing/winit/blob/bfcd85ab150d088be254f43870e7d485f6f95348/src/platform_impl/macos/util/cursor.rs#L21).

Windows has a similar issue that I have already reported: https://github.com/rust-windowing/winit/issues/1043

This issue is related to the example, not Iced itself. In any case, we should try to contribute and fix these!

**Comment by hecrj** [comment]
This should be fixed in `master` :tada:
